### ISSUE TITLE
ERROR: manifest for ptrxyz/chemotion:msconvert-1.2.1p220501 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by QiRae** [ptrxyz/chemotion#15]
Hi, while creating the docker instances I get this error: 

ERROR: manifest for ptrxyz/chemotion:msconvert-1.2.1p220501 not found: manifest unknown: manifest unknown

Can you tell me what to do about it, please? Thank you!

**Comment by raymundfueloep** [comment]
Just ran into the same problem. After poking around in the available docker images/tags, i'd say: the current install is broken.
I edited the docker-compose.yml to circumvent this: change all explicitly mentioned version numbers from 1.2.1p220501 to 1.1.2p220401
This is obviously just a hack until this gets fixed...

**Comment by ptrxyz** [comment]
Fixed in 1.3.0
