### ISSUE TITLE
A few comments

### ISSUE THREAD

**Issue by NicolasCARPi** [ptrxyz/chemotion#7]
**edit**: please excuse the pedantic tone of this issue

Hello,

So I wanted to make some changes to Dockerfiles but I'm running into issues because it seems some things are not easily reproducible out of the box. For instance, trying to build the spectra image: what should be `src` (I'm guessing [this repo](https://github.com/ComPlat/chem-spectra-app) ?), why do I need to download the miniconda.sh script file myself, etc... Same issue with chemotion image: it doesn't work out of the box (even after cloning main repo in src).

Here are some tips that might help you making better docker images:

- don't use `:latest` but pin it to `20.04`, the idea is to be as reproducible as possible every time. That's why doing apt upgrade is frowned upon but if you don't you end up with tons of vulnerabilites in the base image. And this is why you should:
- use alpine linux as base image (if possible ; beware of musl)
- the spectra image should be based on the official miniconda3 image IMHO
- make sure doing a git clone and docker build works wout of the box or provide documentation to setup the env so external contributors can get it to work without too much fiddling
- you can bind mount /etc/localtime:

~~~yaml
volumes:
  - /etc/localtime:/etc/localtime:ro
~~~

Or make the ENV an ARG too so it can be provided at build time for other timezones.

- I don't really get the point of having `mcli`, and the download takes ages because it's using a custom server, and it doesn't seem to be used in scripts or anywhere else as far as I can tell.
- you should look into multi stage docker images so you don't keep build tools in prod image (or do the install build and purge in same RUN)
- instead of cd app_dir/app everytime, use `WORKDIR`
- use shellcheck to look for issues in your bash scripts
- don't install vim for prod image or any other convenience tools (mcli?)
- you install inkscape???
- maybe use official ruby as base image for chemotion? with multistage build for the nodejs part?

Well, I'll stop there ;)

Best,
~Nico

**Comment by ptrxyz** [comment]
Hello,
thanks for your input, some of the points you mention are valid, some are not and some are design decisions we did on purpose. 
I am not a big fan of lists made from 'why u no do this?' and 'you should do XYZ' but I am happy to accept a) pull requests and b) issues to track the concerns one by one. Going through all the points in detail is quite time intensive, messy (as the answers are usually longer than just a one liner) and following (a) and (b) would be of much bigger help.

Closed for now, accepting (a) and (b).

**Comment by NicolasCARPi** [comment]
Yeah sorry I realize this list of stuff thrown around might not be the best approach. As I said, I was going for PR as I agree with you it's much better than this, but had difficulties simply building the images from scratch, so that's why I created this issue, but it got a little bit out of hand and I ended up writing everything going through my mind....

Best,
~Nico

**Comment by JanCBrammer** [comment]
@ptrxyz, any use in me going over @NicolasCARPi suggestions and extracting small, targeted issues?

Should help homing in on potenital areas of improvement. Also it would help documenting/curating design decisions (I'm interested in learning about those).

I feel like it would be good to invest some energy here, since the institutes at Jena and Aachen want to move their deployment / production to Docker in the coming months.
